# This .yml file is used to specify the conda environment that should be loaded into the RTD instance
name: teqpdocs_ntd2d
channels:
  - conda-forge
dependencies:
  - python==3.11
  - pip
  - doxygen
  - cmake
  - pandoc
  - pip:
    - sympy
    - numpy 
    - pandas
    - scipy
    - matplotlib
    - teqp
    - PCSAFTsuperanc
    - sphinxcontrib-doxylink
    - CoolProp
    - jupyter 
    - notebook
    - nbconvert
    - sphinx==7.2.6
    - nbsphinx
