name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: checkout submodules
        run: git submodule update --init --recursive
      - uses: ianhbell/NISTtheDocs2Death@main
        with:
          docs-folder: externals/teqp/doc/
          apt-packages: texlive-font-utils
          conda-environment: environment.yml
          pre-borg-command: python prepare_build.py
          pre-build-command: rm -rf externals/teqp/doc-BORGED/build
          post-borg-command: echo "hi"
          # post-build-command: |-
          #   cp externals/teqp/doc-BORGED/build/latex/teqp.pdf externals/teqp/doc-BORGED/build/latex/teqp-docs.pdf
          #   cp externals/teqp/doc-BORGED/build/latex/teqp.tex externals/teqp/doc-BORGED/build/latex/teqp-docs.tex
          #   cp externals/teqp/doc-BORGED/build/latex/teqp.log externals/teqp/doc-BORGED/build/latex/teqp-docs.log
          formats: |-
            epub
            pdf
